jobs:

 - name: release-single-component_runCI
   type: runCI
   steps:
     - OUT: demo-img
    flags:
      - release-single-component

  - name: demo-man
    type: manifest
    steps:
      - IN: demo-img
      - IN: demo-img-opts
      - TASK: managed
    flags:
      - release-single-component

  - name: deploy-test-ecs
    type: deploy
    steps:
      - IN: demo-man
      - IN: env-aws-ecs-cluster
      - TASK: managed
    flags:
      - release-single-component

  - name: version-deployment
    type: release
    steps:
      - IN: demo-release-version
      - IN: deploy-test-ecs
      - TASK: managed
        bump: beta
    flags:
      - release-single-component
