jobs:

  - name: ci-java-ecr_runCI
    type: runCI
    steps:
      - OUT: ecr-img
    flags:
      - release-multiple-component

  - name: node-img-manifest
    type: manifest
    steps:
      - IN: demo-img
      - IN: demo-img-opts
      - TASK: managed
    flags:
      - release-multiple-component

  - name: java-img-manifest
    type: manifest
    steps:
      - IN: ecr-img
      - IN: ecr-img-opts
      - TASK: managed
    flags:
      - release-multiple-component

  - name: version-multiple-components
    type: release
    steps:
      - IN: java-img-manifest
      - IN: node-img-manifest
      - TASK: managed
        bump: beta
    flags:
      - release-multiple-component

  - name: release-multiple-deploy--ecs
    type: deploy
    steps:
      - IN: version-multiple-components
      - IN: release-multiple-ecs-cluster
      - TASK: managed
    flags:
      - release-multiple-component
